{
  "openapi": "3.0.1",
  "info": {
    "title": "Default module",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/v1/company/contacts": {
      "get": {
        "summary": "List Contacts",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "per_page",
            "in": "query",
            "description": "",
            "required": false,
            "example": "15",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort_by",
            "in": "query",
            "description": "updated_at || placed_orders || total_spent || customer_name, MINUS FOR DESC SORTING",
            "required": false,
            "example": "-placed_orders",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "date_from",
            "in": "query",
            "description": "",
            "required": false,
            "example": "2025-06-01",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "date_to",
            "in": "query",
            "description": "",
            "required": false,
            "example": "2025-12-30",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "region_id",
            "in": "query",
            "description": "",
            "required": false,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "has_orders",
            "in": "query",
            "description": "true || false",
            "required": false,
            "example": "false",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "tags",
            "in": "query",
            "description": "comma separated",
            "required": false,
            "example": "VIP,electronic",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "buyer_type",
            "in": "query",
            "description": "new || repeated",
            "required": false,
            "example": "new",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/v1/company/contacts/{id}": {
      "get": {
        "summary": "Show Contact Details",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "81",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "placed_orders": {
                          "type": "integer"
                        },
                        "paid_orders": {
                          "type": "integer"
                        },
                        "total_spent": {
                          "type": "string"
                        },
                        "avg_order_value": {
                          "type": "string"
                        },
                        "quotes_received": {
                          "type": "integer"
                        },
                        "rfqs_count": {
                          "type": "integer"
                        },
                        "tags": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        },
                        "customer": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "integer"
                            },
                            "name": {
                              "type": "string"
                            },
                            "picture": {
                              "type": "string"
                            },
                            "email": {
                              "type": "string"
                            },
                            "phone": {
                              "type": "string"
                            },
                            "has_company": {
                              "type": "boolean"
                            },
                            "company_name": {
                              "type": "null"
                            }
                          },
                          "required": [
                            "id",
                            "name",
                            "picture",
                            "email",
                            "phone",
                            "has_company",
                            "company_name"
                          ]
                        },
                        "notes": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer"
                              },
                              "note": {
                                "type": "string"
                              },
                              "created_at": {
                                "type": "string"
                              },
                              "updated_at": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "id",
                              "note",
                              "created_at",
                              "updated_at"
                            ]
                          }
                        },
                        "interactions": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "integer"
                              },
                              "interaction_type": {
                                "type": "string"
                              },
                              "description": {
                                "type": "string"
                              },
                              "created_at": {
                                "type": "string"
                              },
                              "updated_at": {
                                "type": "string"
                              },
                              "reference_id": {
                                "type": "null"
                              },
                              "reference_type": {
                                "type": "null"
                              }
                            },
                            "required": [
                              "id",
                              "interaction_type",
                              "description",
                              "created_at",
                              "updated_at",
                              "reference_id",
                              "reference_type"
                            ]
                          }
                        }
                      },
                      "required": [
                        "id",
                        "placed_orders",
                        "paid_orders",
                        "total_spent",
                        "avg_order_value",
                        "quotes_received",
                        "rfqs_count",
                        "tags",
                        "created_at",
                        "updated_at",
                        "customer",
                        "notes",
                        "interactions"
                      ]
                    }
                  },
                  "required": [
                    "data"
                  ]
                },
                "example": {
                  "data": {
                    "id": 1,
                    "placed_orders": 0,
                    "paid_orders": 0,
                    "total_spent": "0.00",
                    "avg_order_value": "0.00",
                    "quotes_received": 1,
                    "rfqs_count": 0,
                    "tags": [
                      "VIP",
                      "Electronics",
                      "Important"
                    ],
                    "created_at": "2025-09-26T07:12:40.000000Z",
                    "updated_at": "2025-09-26T11:51:45.000000Z",
                    "customer": {
                      "id": 168,
                      "name": "Velma Boyle MD",
                      "picture": "https://placehold.co/200/png?text=No+Image",
                      "email": "efren36@example.org",
                      "phone": "+17068867756",
                      "has_company": false,
                      "company_name": null
                    },
                    "notes": [
                      {
                        "id": 1,
                        "note": "test note here",
                        "created_at": "2025-09-26T10:27:38.000000Z",
                        "updated_at": "2025-09-26T10:27:43.000000Z"
                      },
                      {
                        "id": 2,
                        "note": "New Edited Note Here",
                        "created_at": "2025-09-26T11:46:21.000000Z",
                        "updated_at": "2025-09-26T11:49:24.000000Z"
                      }
                    ],
                    "interactions": [
                      {
                        "id": 1,
                        "interaction_type": "call",
                        "description": "Description Here",
                        "created_at": "2025-09-27T05:24:33.000000Z",
                        "updated_at": "2025-09-27T05:24:33.000000Z",
                        "reference_id": null,
                        "reference_type": null
                      },
                      {
                        "id": 2,
                        "interaction_type": "call",
                        "description": "Description Here",
                        "created_at": "2025-09-27T05:27:19.000000Z",
                        "updated_at": "2025-09-27T05:27:19.000000Z",
                        "reference_id": null,
                        "reference_type": null
                      },
                      {
                        "id": 3,
                        "interaction_type": "call",
                        "description": "Description Here",
                        "created_at": "2025-09-27T05:27:32.000000Z",
                        "updated_at": "2025-09-27T05:27:32.000000Z",
                        "reference_id": null,
                        "reference_type": null
                      }
                    ]
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/v1/company/contacts/{id}/tags": {
      "post": {
        "summary": "Edit Tags",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "tags": [
                  "VIP",
                  "Electronics",
                  "Important"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "note": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "placed_orders": {
                          "type": "integer"
                        },
                        "paid_orders": {
                          "type": "integer"
                        },
                        "total_spent": {
                          "type": "string"
                        },
                        "avg_order_value": {
                          "type": "string"
                        },
                        "quotes_received": {
                          "type": "integer"
                        },
                        "rfqs_count": {
                          "type": "integer"
                        },
                        "tags": {
                          "type": "array",
                          "items": {
                            "type": "string"
                          }
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "placed_orders",
                        "paid_orders",
                        "total_spent",
                        "avg_order_value",
                        "quotes_received",
                        "rfqs_count",
                        "tags",
                        "created_at",
                        "updated_at"
                      ]
                    }
                  },
                  "required": [
                    "message",
                    "note"
                  ]
                },
                "example": {
                  "message": "Tags updated successfully",
                  "note": {
                    "id": 1,
                    "placed_orders": 0,
                    "paid_orders": 0,
                    "total_spent": "0.00",
                    "avg_order_value": "0.00",
                    "quotes_received": 1,
                    "rfqs_count": 0,
                    "tags": [
                      "VIP",
                      "Electronics",
                      "Important"
                    ],
                    "created_at": "2025-09-26T07:12:40.000000Z",
                    "updated_at": "2025-09-26T11:51:45.000000Z"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/v1/company/contacts/{id}/note": {
      "post": {
        "summary": "Add Note",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "note": "New Note Here"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "note": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "note": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "note",
                        "created_at",
                        "updated_at"
                      ]
                    }
                  },
                  "required": [
                    "message",
                    "note"
                  ]
                },
                "example": {
                  "message": "Note created successfully",
                  "note": {
                    "id": 2,
                    "note": "New Note Here",
                    "created_at": "2025-09-26T11:46:21.000000Z",
                    "updated_at": "2025-09-26T11:46:21.000000Z"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/v1/company/contacts/{contactId}/note/{noteId}": {
      "put": {
        "summary": "Edit Note",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "noteId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "2",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {
                "note": "New Edited Note Here"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "note": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "note": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "note",
                        "created_at",
                        "updated_at"
                      ]
                    }
                  },
                  "required": [
                    "message",
                    "note"
                  ]
                },
                "example": {
                  "message": "Note updated successfully",
                  "note": {
                    "id": 2,
                    "note": "New Edited Note Here",
                    "created_at": "2025-09-26T11:46:21.000000Z",
                    "updated_at": "2025-09-26T11:49:24.000000Z"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      },
      "delete": {
        "summary": "Delete Note",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "contactId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "noteId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "2",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "note": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "note": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "id",
                        "note",
                        "created_at",
                        "updated_at"
                      ]
                    }
                  },
                  "required": [
                    "message",
                    "note"
                  ]
                },
                "example": {
                  "message": "Note updated successfully",
                  "note": {
                    "id": 2,
                    "note": "New Edited Note Here",
                    "created_at": "2025-09-26T11:46:21.000000Z",
                    "updated_at": "2025-09-26T11:49:24.000000Z"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/v1/company/contacts/{id}/interaction": {
      "post": {
        "summary": "Add Interaction",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": "{\n    \"interaction_type\": \"call\", // call || email || meeting || order || other\n    \"title\": \"Interaction Title Here\",\n    \"details\": \"Description Here\" // Nullable\n}"
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "interaction": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "interaction_type": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        },
                        "reference_id": {
                          "type": "null"
                        },
                        "reference_type": {
                          "type": "null"
                        }
                      },
                      "required": [
                        "id",
                        "interaction_type",
                        "description",
                        "created_at",
                        "updated_at",
                        "reference_id",
                        "reference_type"
                      ]
                    }
                  },
                  "required": [
                    "message",
                    "interaction"
                  ]
                },
                "example": {
                  "message": "Interaction added successfully",
                  "interaction": {
                    "id": 3,
                    "interaction_type": "call",
                    "description": "Description Here",
                    "created_at": "2025-09-27T05:27:32.000000Z",
                    "updated_at": "2025-09-27T05:27:32.000000Z",
                    "reference_id": null,
                    "reference_type": null
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    },
    "/api/v1/company/contacts/export": {
      "post": {
        "summary": "Export Contacts",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": "{\n    // \"date_from\": \"2025-01-01\", // Optional\n    // \"date_to\": \"2025-12-12\", // Optional\n    // \"region_id\": 2,\n    // \"ids\": [2, 4], // Optional\n    \"format\": \"xlsx\" // csv || xlsx\n}"
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "interaction": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "interaction_type": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        },
                        "created_at": {
                          "type": "string"
                        },
                        "updated_at": {
                          "type": "string"
                        },
                        "reference_id": {
                          "type": "null"
                        },
                        "reference_type": {
                          "type": "null"
                        }
                      },
                      "required": [
                        "id",
                        "interaction_type",
                        "description",
                        "created_at",
                        "updated_at",
                        "reference_id",
                        "reference_type"
                      ]
                    }
                  },
                  "required": [
                    "message",
                    "interaction"
                  ]
                },
                "example": {
                  "message": "Interaction added successfully",
                  "interaction": {
                    "id": 3,
                    "interaction_type": "call",
                    "description": "Description Here",
                    "created_at": "2025-09-27T05:27:32.000000Z",
                    "updated_at": "2025-09-27T05:27:32.000000Z",
                    "reference_id": null,
                    "reference_type": null
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [],
  "security": [
    {
      "bearer": []
    }
  ]
}